// Re-export shared Zod schemas (read-only at this phase per CLAUDE.md §8).
export {
  jcDocInputSchema,
  jcOpInputSchema,
  jobCardCreateInputSchema,
  jobCardDocSchema,
  jobCardEditModelSchema,
  jobCardListItemSchema,
  jobCardOpEditSchema,
  jobCardSourceLinkSchema,
  jobCardSourceOptionSchema,
  jobCardSourceSoLinkSchema,
  jobCardSourceJwLinkSchema,
  jobCardUpdateInputSchema,
  jobCardWriteInputSchema,
  listJobCardsQuerySchema,
} from '@innovic/shared';
export type {
  JcDocInput,
  JcOpInput,
  JobCardCreateInput,
  JobCardDoc,
  JobCardEditModel,
  JobCardListItem,
  JobCardOpEdit,
  JobCardSourceLink,
  JobCardSourceOption,
  JobCardUpdateInput,
  JobCardWriteInput,
  ListJobCardsQuery,
  ListJobCardsResponse,
} from '@innovic/shared';
